# Generated by Django 5.0.6 on 2024-07-06 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(help_text='Введите заголовок', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Введите текст', verbose_name='Текст')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='blog/images', verbose_name='Изображение')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views_count', models.IntegerField(default=0, verbose_name=' Просмотры')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slug')),
                ('author', models.ForeignKey(blank=True, help_text='Введите автора', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'permissions': [('can_edit_publication', 'Can edit publication'), ('can_edit_tittle', 'Can edit tittle'), ('can_edit_text', 'Can edit text'), ('can_edit_image', 'Can edit image')],
            },
        ),
    ]
