# Generated by Django 5.0.6 on 2024-07-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailing_options_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='time_send',
            field=models.TimeField(default='12:00', verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='end_mailing',
            field=models.DateField(default='01.01.2100', verbose_name='Дата окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_mailing',
            field=models.DateField(verbose_name='Дата начала рассылки'),
        ),
    ]
