# Generated by Django 5.0.6 on 2024-07-05 10:11

import datetime
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_mailing_time_send_alter_mailing_end_mailing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='time_send',
            new_name='time_sending',
        ),
        migrations.AddField(
            model_name='mailing',
            name='next_sending',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующей отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='end_mailing',
            field=models.DateField(default=datetime.date(2025, 7, 5), verbose_name='Дата окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_mailing',
            field=models.DateField(default=django.db.models.functions.datetime.Now(), verbose_name='Дата начала рассылки'),
        ),
    ]
