# Generated by Django 5.0.6 on 2024-07-06 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_rename_time_send_mailing_time_sending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_mailing',
            field=models.DateField(default=datetime.date(2025, 7, 6), verbose_name='Дата окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_mailing',
            field=models.DateField(default=datetime.date(2024, 7, 6), verbose_name='Дата начала рассылки'),
        ),
    ]
